#file: noinspection YAMLSchemaValidation
version: '3'

tasks:
  c1-deploy-local:
    cmds:
      - sam build -u -t template.yaml --skip-pull-image
      - sam local invoke C1LambdaFunction --event events/no_data.json
  c1-deploy:
    cmds:
      - sam build -t template.yaml
      - sam deploy --no-confirm-changeset
  behave:
    cmds:
      - behave
  bsid:
    cmds:
      - sl-python config --appname c1-lambda --tokenfile ./sltoken.txt --exclude "*tests*,*venv*,*sealights_layer*,*dynatrace_python_agent*,*sl*"
  scan:
    cmds:
      - sl-python scan --buildsessionidfile ./buildSessionId.txt --tokenfile ./sltoken.txt

  configlambda:
    cmds:
      - sl-python configlambda --slconfigpaths "./api" --collectorurl "https://a07a-46-120-32-95.ngrok-free.app" --exportlayerpath "./" -
